### PR TITLE
pkp/pkp-lib#4273: add breadcrumbs

### PR DESCRIPTION
**Pull request by ctgraham**
Addresses pkp/pkp-lib#4273 for Static Pages plugin.

### CODE REVIEW

**Comment by asmecher** [comment]
@ctgraham, have you looked at the tests? At a glance, this appears to break them.

**Comment by ctgraham** [comment]
Tests in plugins.  How modern of us.

**Comment by ctgraham** [comment]
Well, hrmm....  Still failing.

**Comment by asmecher** [comment]
The problem is that the change removes the header element that the test is looking for: https://github.com/pkp/staticPages/blob/34d86be0b3768558072a0809c9807d427946773f/tests/functional/StaticPagesFunctionalTest.php#L82

**Comment by ctgraham** [comment]
But it adds the `nav.cmp_breadcrumbs > ol > li.current > h1`, which I thought would be matched by `'//nav//li.current//h1[contains(text(),\'Test Static Page\')]'`.

I'll get a moment to really look at it eventually.

**Pull request closed without merging**
